### ISSUE TITLE
Is this a Pretrained model?

### ISSUE THREAD

**Issue by YK-YR** [zweny/RE-Matching#1]
Can I directly use this model to achieve some relation extraction tasks without training?

**Comment by zweny** [comment]
We use BERT(or roberta\ albert ) as the foundation model for our experiments. Direct application of these models to downstream tasks ( e.g., relation extraction ) does not yield satisfactory results. you'll need to do some fine-tuning If you want to do relation extraction task :)

**Comment by YK-YR** [comment]
Thank you for your advices. I get it.
